version: "3.8"

services:
  app:
    restart: always
    build: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: postgres://postgres@pg/postgres
      BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    command: mix phx.server
    depends_on:
      - pg
  pg:
    image: postgres:12.5-alpine
    volumes:
      - ./db/postgres/tmp/data:/var/lib/postgresql/data
