version: "3.9"

services:
  db:
    image: postgres:12.5-alpine
    volumes:
      - ./_local/db/:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  app:
    restart: always
    build: .
    volumes:
      - .:/usr/src/${PROJECT_NAME}
    ports:
      - 4000:4000
    env_file:
      - .env.dev
    environment:
      MIX_ENV: dev
    command:
      bash -c "cd ${PROJECT_NAME} && mix phx.server"
    depends_on:
      - db
