version: "3.9"

services:
  postgres:
    image: postgres:15.1-alpine
    volumes:
      - ./_local/db/:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  app:
    restart: always
    build: .
    volumes:
      - .:/usr/src/${PROJECT_NAME}
    ports:
      - 4000:4000
    env_file:
      - .env.dev
    environment:
      MIX_ENV: prod # for tailwindcss
    command:
      bash -c "mix phx.server"
    depends_on:
      - postgres
